<a href="https://colab.research.google.com/github/TABEYWICKRAMA/Python_series_end-to-end/blob/Numpy/Basics%20of%20NumPy%20library.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
name = "Oshada"
no_studs=150
temp = 13.0
print(name)
print(no_studs)
print(temp)


Oshada
150
13.0


In [6]:
List_1 = [1,2,3,4,5,6,7,8,9,10]
List_2 = list(range(0,20))
List_3 = [x for x in range(10)]
List_1


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
List_2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [8]:
List_3

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
for e in List_1:
 if e%2 != 0:
   print(e)


1
3
5
7
9


In [12]:
i = 0
while i <len(List_1):
 if List_1[i] %2 != 0:
  print(List_1[i])
 i+=1

1
3
5
7
9


In [13]:
List_5 = [x for x in List_1 if x%2 !=0]
print(List_5)

[1, 3, 5, 7, 9]


In [17]:
#This will print square of odd numbers between 0 to 9
#output
#1 
#9
#25
#49

l6 = [x for x in [x**2 for x in range(9)] if x%2 !=0]
print(l6)


[1, 9, 25, 49]


In [16]:
def get_odd(n):
 return [x for x in [x**2 for x in range(n)] if x%2 !=0]


In [18]:
get_odd(4)

[1, 9]

In [19]:
d1 = {x : x**2 for x in range(7)}
print(d1)


{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36}


In [20]:
vals=list(d1.values())
vals


[0, 1, 4, 9, 16, 25, 36]

In [21]:
a = [0,1,2,3,4,5]
a[::-1]

[5, 4, 3, 2, 1, 0]

In [26]:
xcoors=[0,1,2,3,4,5]
ycoors=[6,7,8,9,10,11]

In [27]:
zip_list=list(zip(xcoors,ycoors))


In [28]:
zip_list

[(0, 6), (1, 7), (2, 8), (3, 9), (4, 10), (5, 11)]

In [29]:
unzip_list=list(zip(*zip_list))

In [30]:
unzip_list

[(0, 1, 2, 3, 4, 5), (6, 7, 8, 9, 10, 11)]

In [31]:
###### Numpy
import numpy as np


In [32]:
#Create an numpy array of floats containing the numbers from 0 to 4.
arr0 = np.array([0,1,2,3,4], float)
print(arr0)

[0. 1. 2. 3. 4.]


In [34]:
#Create the following matrix as a numpy matrix: M=[[1,2,3],[4,5,6]].
arr1 = np.array([[1,2,3],[4,5,6]], float)
print(arr1)

[[1. 2. 3.]
 [4. 5. 6.]]


In [35]:
#Get the shape of the matrix M. Check if the value 2 is in M.
arr1.shape

(2, 3)